version: '3.2'
services:
   proxy:
      image: registry:5000/highmed/fhir_proxy
      restart: on-failure
      ports:
      - 80:80
      - 443:443
      volumes:
      -  type: bind
         source: ./proxy/ssl
         target: /usr/local/apache2/ssl
         read_only: true
      environment:
         TZ: Europe/Berlin
         HTTPS_SERVER_NAME_PORT: ttp:443
         APP_SERVER_IP: 172.28.1.3
      networks:
         frontend:
            ipv4_address: 172.28.1.2
         bpe:
            ipv4_address: 172.28.2.2
            aliases:
            - fhir
      depends_on:
      - app
   app:
      image: registry:5000/highmed/fhir
      restart: on-failure
      volumes:
      -  type: bind
         source: ./app/conf
         target: /opt/fhir/conf
         read_only: true
      -  type: bind
         source: ./app/log
         target: /opt/fhir/log
      environment:
         TZ: Europe/Berlin
      networks:
         frontend:
            ipv4_address: 172.28.1.3
         backend:
            ipv4_address: 172.28.1.130
      extra_hosts:
      - "ttp:10.42.0.10"
      - "medic1:10.42.0.11"
      - "medic2:10.42.0.12"
      - "medic3:10.42.0.13"
      depends_on:
      - db
   db:
      image: postgres:13
      restart: on-failure
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U liquibase_user -d fhir"]
         interval: 10s
         timeout: 5s
         retries: 5
      environment:
         TZ: Europe/Berlin
         POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
         POSTGRES_USER: liquibase_user
         POSTGRES_DB: fhir
      networks:
         backend:
            ipv4_address: 172.28.1.131
      secrets:
      - postgres_password
secrets:
   postgres_password:
      file: ./db/conf/postgres_password
networks:
   frontend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.1.0/25
   backend:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.1.128/25
   bpe:
      driver: bridge
      ipam:
         driver: default
         config:
         -  subnet: 172.28.2.0/24